version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
  # We want updates for our pinned base image.
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
  # We vendor pg_plan_filter using a git submodule.
  - package-ecosystem: gitsubmodule
    directory: '/'
    schedule:
      interval: weekly
